//
//  GeneratedMocks.swift
//  HobbyHangarTests
//
//  This file is auto-generated by Cuckoo during the build process.
//  Do not edit manually - changes will be overwritten.
//
//  Build the HobbyHangarTests target to regenerate mocks for:
//  - DBRepository (HobbyHangar/Repositories/DBRepository.swift)
//  - PilotService protocols (HobbyHangar/Services/PilotService.swift)
//

import Foundation

// Placeholder file - Cuckoo will generate mock classes here on build.
// If you see this content after building, check the "Generate Cuckoo Mocks"
// build phase in the HobbyHangarTests target.
