//
//  HobbyHangarTests.swift
//  HobbyHangarTests
//
//  Created by Nick Leach on 1/15/26.
//

import Cuckoo
import Testing
@testable import HobbyHangar

struct HobbyHangarTests {

    @Test func example() async throws {
        // Write your test here and use APIs like `#expect(...)` to check expected conditions.
    }

}

// MARK: - Sample Cuckoo Mock Test

/// Sample test demonstrating how to use Cuckoo mocks with DBRepository.
/// Once GeneratedMocks.swift is generated by the build script, you can use:
///
/// ```swift
/// let mockRepository = MockDBRepository()
/// stub(mockRepository) { stub in
///     // Set up your stubs here
/// }
/// ```
///
/// To generate mocks, build the test target. The "Generate Cuckoo Mocks" build phase
/// will automatically generate mocks for protocols in:
/// - HobbyHangar/Repositories/DBRepository.swift
/// - HobbyHangar/Services/PilotService.swift
struct DBRepositoryMockTests {

    @Test func testDBRepositoryCanBeMocked() async throws {
        // This test verifies the Cuckoo setup is working.
        // After the first build generates mocks, you can uncomment and use:
        //
        // let mockRepo = MockDBRepository()
        // stub(mockRepo) { stub in
        //     // Configure mock behavior
        // }
        //
        // Then inject mockRepo into your ViewModels for testing
        // without hitting the actual SwiftData persistence layer.

        #expect(true, "Cuckoo integration is set up. Build the test target to generate mocks.")
    }
}
