default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    setup_ci
    
    delete_keychain(name: "fastlane_tmp_keychain") if File.exist?("#{Dir.home}/Library/Keychains/fastlane_tmp_keychain-db")
    create_keychain(
      name: "fastlane_tmp_keychain",
      password: "fastlane_password",
      default_keychain: true,
      unlock: true,
      timeout: 3600
    )

    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_CONTENT"],
      is_key_content_base64: false
    )

    match(
      type: "appstore",
      readonly: true,
      api_key: api_key,
      keychain_name: "fastlane_tmp_keychain",
      keychain_password: "fastlane_password"
    )

    build_app(
      project: "HobbyHangar.xcodeproj",
      scheme: "HobbyHangar",
      export_method: "app-store",
      clean: true,
      xcargs: "-skipPackagePluginValidation"
    )

    upload_to_testflight(
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end